services:
  cloudflare:
    image: cloudflare/cloudflared:2026.2.0
    volumes:
      - ./.cloudflare/volumes:/home/nonroot/.cloudflared
    restart: unless-stopped
    # network_mode: host
    networks:
      - default
    command: tunnel run blog_chat
  app:
    build: .
    ports:
      - "9091:9091"
    restart: unless-stopped
  
networks:
  default: