services:
  app:
    build: .
    ports:
      - "9091:9091"
    restart: unless-stopped
    networks:
      - blog_chat
  cloudflare:
    image: cloudflare/cloudflared:2026.2.0
    volumes:
      - ./.cloudflare/volumes:/home/nonroot/.cloudflared
    restart: unless-stopped
    # network_mode: host
    networks:
      - blog_chat
    command: tunnel run blog_chat

networks:
  blog_chat: